AWSTemplateFormatVersion: "2010-09-09"

Description: IaC using vscode in web console. (Cloud Formation).

Parameters:
  Region:
    Type: String
    Default: ap-northeast-2
    AllowedValues:
    - ap-northeast-2
    - ap-northeast-1

  WebVscodeVPCCidr:
    Type: String
    Default: 10.111.0.0/16
    Description: Web vscode VPC cidr

  WebVscodePublicSubnetCidr:
    Type: String
    Default: 10.111.8.0/24
    Description: Web vscode public subnet cidr

  WebVscodeSSHKeyName:
    Type: String
    Default: hwani_key
    Description: Web vscode ec2 ssh key name

Mappings: 
  AvailabilityZone:
    Seoul:
      A: ap-northeast-2a
      B: ap-northeast-2b
      C: ap-northeast-2c
      D: ap-northeast-2d
    Tokyo:
      A: ap-northeast-1a
      B: ap-northeast-1b
      C: ap-northeast-1c
      D: ap-northeast-1d

  AWSRegionAMI:
    Seoul:
      Ubuntu: ami-04876f29fd3a5e8ba
    Tokyo:
      Ubuntu: ami-0df99b3a8349462c6

Resources:

  WebVscodeVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref WebVscodeVPCCidr
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: Web vscode vpc

  WebVscodeInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
      - Key: Name
        Value: Web vscode internet gateway

  WebVscodeInternetGatewayVPCAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref WebVscodeInternetGateway
      VpcId: !Ref WebVscodeVPC

  WebVscodePublicSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !FindInMap [ AvailabilityZone, Seoul, A ]
      CidrBlock: !Ref WebVscodePublicSubnetCidr
      Tags: 
      - Key: Name
        Value: Web vscode public subnet
      VpcId: !Ref WebVscodeVPC

  WebVscodePublicSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref WebVscodeVPC
      Tags:
      - Key: Name
        Value: Web vscode public subnet route table      

  WebVscodePublicSubnetRoute:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref WebVscodeInternetGateway
      RouteTableId: !Ref WebVscodePublicSubnetRouteTable

  WebVscodeSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref WebVscodePublicSubnetRouteTable
      SubnetId: !Ref WebVscodePublicSubnet      
      
  WebVscodeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Web vscode SG
      GroupName: Web vscode SG(hwan)
      SecurityGroupEgress: 
      - CidrIp: 0.0.0.0/0
        Description: HTTPS Outbound
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
      - CidrIp: 0.0.0.0/0
        Description: HTTP Outbound
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80     
      SecurityGroupIngress: 
      - CidrIp: 0.0.0.0/0
        Description: SSH Inbound
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        Description: HTTPS Outbound
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
      - CidrIp: 0.0.0.0/0
        Description: HTTP Outbound
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80        
      Tags:
      - Key: Name
        Value: Web vscode SG
      VpcId: !Ref WebVscodeVPC

  WebVscodeEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !FindInMap [ AvailabilityZone, Seoul, A ]
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeleteOnTermination: true
        DeviceIndex: 0
        GroupSet: 
        - !Ref WebVscodeSecurityGroup
        SubnetId: !Ref WebVscodePublicSubnet
        Description: Web vscode ec2 interface
      ImageId: !FindInMap [ AWSRegionAMI, Seoul, Ubuntu ]
      InstanceType: t2.micro
      KeyName: !Ref WebVscodeSSHKeyName
      Tags:
      - Key: Name
        Value: Web vscode server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          
          apt update

          # install code-server service system-wide
          export HOME=/root
          curl -fsSL https://code-server.dev/install.sh | sh

          # add our helper server to redirect to the proper URL for --link
          git clone https://github.com/bpmct/coder-cloud-redirect-server
          cd coder-cloud-redirect-server
          cp coder-cloud-redirect.service /etc/systemd/system/
          cp coder-cloud-redirect.py /usr/bin/

          # create a code-server user
          adduser --disabled-password --gecos "" coder
          echo "coder ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/coder
          usermod -aG sudo coder

          # copy ssh keys from root
          cp -r /root/.ssh /home/coder/.ssh
          chown -R coder:coder /home/coder/.ssh

          # configure code-server to use --link with the "coder" user
          mkdir -p /home/coder/.config/code-server
          touch /home/coder/.config/code-server/config.yaml
          echo "link: true" > /home/coder/.config/code-server/config.yaml
          chown -R coder:coder /home/coder/.config

          # start and enable code-server and our helper service
          systemctl enable --now code-server@coder
          systemctl enable --now coder-cloud-redirect
          